name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Notification on PR
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "Novo Pull Request criado em ${GITHUB_REPOSITORY} por ${GITHUB_ACTOR}"}' \
             https://webhook.site/60456568-6957-4141-8deb-207cd5152379
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build -t apeportob/my-app-nodejs .
        docker push apeportob/my-app-nodejs:latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: echo "Run tests here"
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_HOST_URL: "https://sonarcloud.io"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Ngrok
      run: ngrok http 3000
