name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Notification on PR
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "Novo Pull Request criado em ${GITHUB_REPOSITORY} por ${GITHUB_ACTOR}"}' \
             https://webhook.site/60456568-6957-4141-8deb-207cd5152379
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build -t apeportob/my-app-nodejs .
        docker push apeportob/my-app-nodejs:latest

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Sonarqube
      run: echo "Run tests here"
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_HOST_URL: "https://sonarcloud.io"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to AWS Elastic Beanstalk
      run: echo "Deployment happening here"
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "my-app-nodejs"
        environment_name: "production"
        region: "us-west-2" 
        version_label: "v-${{ github.run_number }}"
        zip_file: "path/to/your/zip/file"
